---

grafana_security:
  admin_user: admin
  admin_password: admin
  
# Datasources to configure
grafana_datasources: 
  - name: "telegraf"
    access: proxy
    basicAuth: false
    database: telegraf
    editable: false
    type: influxdb
    url: "http://localhost:8086"

  - name: "campus"
    access: proxy
    basicAuth: false
    database: campus
    editable: false
    type: influxdb
    url: "http://localhost:8086"


