---

- hosts: viewer
  become: True
  vars:
    ansible_user: pi
    ansible_ssh_private_key_file: ~/.ssh/iot_master

  tasks:
  - name: Install nodered server 
    apt: 
      name: nodered
      state: present
    tags: ['nodered'] 

  - name: Install npm package manager for Node.js
    apt: 
      name: npm
      state: present
    tags: ['nodered'] 

  - name: Install "node-red-admin" node.js package.
    npm:
      name: node-red-admin
      global: yes
    tags: ['nodered'] 

  - name: Start and enable nodered service
    service: name=nodered state=started enabled=yes 
    tags: [ 'service', 'nodered' ]

  - name: Install grafana server 
    apt: 
      deb: https://github.com/fg2it/grafana-on-raspberry/releases/download/v5.1.4/grafana_5.1.4_armhf.deb
      state: present
    tags: ['grafana'] 

  - name: Start and enable grafana service
    service: name=grafana-server state=started enabled=yes 
    tags: [ 'service', 'grafana' ]

  - name: Create/Update datasources file (provisioning)
    copy:
      dest: "/etc/grafana/provisioning/datasources/ansible.yml"
      content: |
        apiVersion: 1
        delete_datasources: []
        datasources: 
        {{ grafana_datasources | to_nice_yaml }}
      backup: false
    become: true
    notify: restart grafana
    tags: [ 'config', 'grafana', 'grafana_config' ]

  - name: Install nginx server 
    apt: 
      name: nginx
      state: present
    tags: ['nginx'] 

  handlers:
  - name: restart grafana
    become: true
    service:
      name: grafana-server
      state: restarted
